educacion_continua2/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('administrativo/proveedores/', include("administrativo.proveedores.urls")),
	path('ventas/personas_juridicas/', include("ventas.personas_juridicas.urls")),
	path('ventas/reporte_contacto/', include("ventas.reporte_contacto.urls")),
    path('ventas/personas_naturales/', include("ventas.personas_naturales.urls")),
    path('ventas/propuesta_corp/', include("ventas.propuesta_corp.urls")),
    path('ventas/proformas/',include("ventas.proformas.urls")),
    path('ventas/interesados/',include("ventas.interesados.urls")),
    path('financiero/perfiles/', include('financiero.perfiles.urls')),
    path('financiero/orden_Ingreso/',include('financiero.orden_ingreso.urls')),
    path('financiero/orden_facturacion/',include('financiero.orden_facturacion.urls')),
    path("financiero/presupuestos/",include("financiero.presupuestos.urls")),
    path("financiero/orden_pago/",include("financiero.orden_pago.urls")),
    path("financiero/pago_eventos/",include("financiero.pago_eventos.urls")),
    path("financiero/presupuestos_anuales/",include("financiero.presupuestos_anuales.urls")),
    path("financiero/plan_anual_compras/",include("financiero.plan_anual_compras.urls")),
    path("financiero/procesos_especiales/",include("financiero.procesos_especiales.urls")),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

financiero/orden_pago/urls.py
from django.urls import path
from django_filters.views import FilterView
from . import views
from .filters import OrdenPagoFilter

urlpatterns = [
    path("", views.index, name="orden_pago_lista"),
    path("ajax/load-egresos/", views.load_egresos, name="ajax_load_egresos"),
    path("ajax/load-proveedor/", views.load_proveedor, name="ajax_load_proveedor"),
    path("nuevo/", views.orden_pago_nuevo, name="orden_pago_nuevo"),
    path("editar/<pk>", views.orden_pago_editar, name="orden_pago_editar"),
    path("editar_autrAnalista/<pk>",views.orden_pago_editarAUTR_analista, name="orden_pago_editarAUTR_analista"),
    path("editar_postAUTR/<pk>",views.orden_pago_editarPOST_AUTR, name="orden_pago_editarPOST_AUTR"),
    path("editar_PGDO/<pk>",views.orden_pago_editarPGDO, name="orden_pago_editarPGDO"),
    path("editar_autr/<pk>", views.orden_pago_editarAUTR, name="orden_pago_editarAUTR"),
    path("enviar_solicitud/<pk>", views.orden_pago_enviar, name="orden_pago_enviar"),
    path("autorizar/<pk>", views.orden_pago_autorizar, name="orden_pago_autorizar"),
    path("anular/", views.orden_pago_anular, name="orden_pago_anular"),
    path("anular/<pk>", views.orden_pago_anular, name="orden_pago_anular"),
]

financiero/orden_pago/models.py
from django.db import models

# Create your models here.

"""class Lista_Rubros(models.Model):
	nombre = models.CharField(max_length=50)
	def __str__(self):
		return self.nombre"""

class Centro_Costos(models.Model):
	nombre = models.CharField(max_length=10)
	espol=models.DecimalField(max_digits=10, decimal_places=2)
	espoltech=models.DecimalField(max_digits=10, decimal_places=2)
	ministerio=models.DecimalField(max_digits=10, decimal_places=2)
	fundaespol=models.DecimalField(max_digits=10, decimal_places=2)

	def __str__(self):
		return self.nombre


class Egresos(models.Model):
	codigo = models.CharField(max_length=15)
	nombre = models.CharField(max_length=200)
	centroc = models.ForeignKey(Centro_Costos, on_delete=models.CASCADE)

	def __str__(self):
		return self.nombre


class OrdenPago(models.Model):
	ESTADO_CHOICES = [("GRBD","Grabado"),("ENVD","Enviado"),("AUTR","Autorizado"),("ANLD","Anulado"),("PGDO","Pagado")]
	FORMAPAGO_CHOICES = [("TR","Transferencia"),("CH","Cheque"),]
	PROVEEDORES_CHOICES = [("Natural", "Natural"),("Jurídica", "Jurídica"),]
	COMPROBANTE_CHOICES = [("FC","Factura"),("NV","Nota de venta"),("LC","Liquidación de compra"),("CP","Comprobantes de pago"),]

	cod_ord_pago = models.CharField(max_length=15, blank=True, null=True)
	n_tramite = models.CharField(max_length=15, blank=True, null=True)
	fecha = models.CharField(max_length=30)
	fecha_tramite = models.CharField(max_length=30)
	fecha_pago = models.CharField(max_length=30)
	estado = models.CharField(max_length=5, default="GRBD",choices=ESTADO_CHOICES, blank=True, null=True)
	tipo_proveedor = models.CharField(max_length=10, choices=PROVEEDORES_CHOICES, blank=False, null=True)
	proveedor = models.CharField(max_length=200)
	centro_costos = models.ForeignKey(Centro_Costos, on_delete=models.SET_NULL, blank=False, null=True)
	egreso = models.ForeignKey(Egresos, on_delete=models.SET_NULL, blank=False, null=True)
	tipo_comprobante = models.CharField(max_length=5, choices=COMPROBANTE_CHOICES, blank=False, null=True)
	n_comprobante = models.CharField(max_length=20, blank=True, null=True)
	concepto = models.CharField(max_length=500)
	forma_pago = models.CharField(max_length=5, choices=FORMAPAGO_CHOICES, blank=False, null=True)
	observacion = models.CharField(max_length=500, blank=True, null=True)
	documentos=models.CharField(max_length=500, blank=True, null=True)
	anexo = models.FileField(upload_to='uploads/orden_pago/', blank=True, null=True)
	motivo_anular = models.CharField(max_length=500, blank=True, null=True)
	

	def __str__(self):
		return self.cod_ord_pago

	def delete(self, *arg, **kwargs):
		self.anexo.delete()
		super().delete(*arg,**kwargs)


"""class Rubro(models.Model):
	orden_pago = models.ForeignKey(OrdenPago, on_delete=models.SET_NULL, blank=True, null=True)
	#nombre_rubro = models.ForeignKey(Lista_Rubros, on_delete=models.SET_NULL, blank=True, null=True)
	cod_evento = models.CharField(max_length=15)
	act_prod = models.CharField(max_length=50)
	c_c = models.PositiveIntegerField()
	subtotal = models.DecimalField(decimal_places=2)
	iva = models.DecimalField(decimal_places=2)
	otros_cargos = models.DecimalField(decimal_places=2)
	total = models.DecimalField(decimal_places=2)
	centro_costos = models.CharField(max_length=100)

	def __str__(self):
		return self.cod_evento+" - "+self.act_prod"""

financiero/orden_pago/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import OrdenPagoForm, OrdenPagoEditarFinalForm, OrdenPagoEditarThirdForm, OrdenPagoEditarFirstForm, OrdenPagoEditarSecondForm
from .models import OrdenPago, Centro_Costos, Egresos
from ventas.personas_naturales.models import Persona_Natural
from ventas.personas_juridicas.models import Juridica
from .filters import OrdenPagoFilter
from django.views.generic import ListView,CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy
from datetime import date
from django.template.loader import render_to_string
from django.http import JsonResponse

# Create your views here.

def index(request):
	if (request.GET.get('estado',None)!=None and 'ANLD' in request.GET['estado']):
		ordPago_lista = OrdenPago.objects.all()
	else:
		ordPago_lista = OrdenPago.objects.all().exclude(estado='ANLD')
	ordPago_filter = OrdenPagoFilter(request.GET, queryset=ordPago_lista)
	return render(request, "orden_pago/ordenpago_list.html", {"ordenes_pago":ordPago_lista, "filter":ordPago_filter})


def load_egresos(request):
	centroc_id = request.GET.get("centroc")
	egresos = Egresos.objects.filter(centroc_id=centroc_id).order_by("nombre")
	return render(request, "orden_pago/dropdown_egresos.html", {"egresos":egresos})


def load_proveedor(request):
	tipo = request.GET.get("tipo")
	proveedor = []
	if(tipo == "Natural"):
		naturales = Persona_Natural.objects.all().order_by("apellidos")
		proveedor = render_to_string("orden_pago/dropdown_naturales.html", {"proveedor":naturales})
	elif(tipo == "Jurídica"):
		juridicas = Juridica.objects.all().order_by("nombre")
		proveedor = render_to_string("orden_pago/dropdown_juridica.html", {"proveedor":juridicas})
	return JsonResponse({"pro":proveedor})


def orden_pago_nuevo(request):
	if(request.method == "POST"):
		form = OrdenPagoForm(request.POST)
		if(form.is_valid()):
			try:
				pre = str(int(OrdenPago.objects.latest('pk').pk+1))
				sec = '0'*(4-len(pre))+pre
			except OrdenPago.DoesNotExist:
				sec = '0001'
			form.instance.cod_ord_pago = sec+'-'+str(date.today().year)
			form.save()
			return redirect("orden_pago_lista")
	else:
		form = OrdenPagoForm()
	return render(request, "orden_pago/ordenpago_nuevo.html", {"form":form})


def orden_pago_editar(request, pk):
	if(request.method == 'POST'):
		p = get_object_or_404(OrdenPago, pk=pk)
		form = OrdenPagoForm(request.POST, instance=p)
		if(form.is_valid()):
			form.save()
			return redirect('orden_pago_lista')
	else:
		p = get_object_or_404(OrdenPago, pk=pk)
		form = OrdenPagoForm(instance=p)
	return render(request, 'orden_pago/ordenpago_editar_1.html', {'form': form})


def orden_pago_editarAUTR_analista(request, pk):
	if(request.method == 'POST'):
		p = get_object_or_404(OrdenPago, pk=pk)
		form = OrdenPagoEditarSecondForm(request.POST, instance=p)
		if(form.is_valid()):
			form.save()
			return redirect('orden_pago_lista')
	else:
		p = get_object_or_404(OrdenPago, pk=pk)
		form = OrdenPagoEditarSecondForm(instance=p)
	return render(request, 'orden_pago/ordenpago_editar_1.html', {'form': form})


def orden_pago_editarAUTR(request, pk):
	if(request.method == 'POST'):
		p = get_object_or_404(OrdenPago, pk=pk)
		form = OrdenPagoEditarSecondForm(request.POST, instance=p)
		if(form.is_valid()):
			form.save()
			return redirect('pendiente_aprobacion')
	else:
		p = get_object_or_404(OrdenPago, pk=pk)
		form = OrdenPagoEditarSecondForm(instance=p)
	return render(request, 'orden_pago/ordenpago_autorizar.html', {'form': form, "p":p})

def orden_pago_editarPOST_AUTR(request, pk):
	if(request.method == 'POST'):
		p = get_object_or_404(OrdenPago, pk=pk)
		form = OrdenPagoEditarThirdForm(request.POST, request.FILES, instance=p)
		if(form.is_valid()):
			form.save()
			p = get_object_or_404(OrdenPago, pk=pk)
			p.estado = 'PGDO'
			p.save()
			return redirect('orden_pago_lista')
	else:
		p = get_object_or_404(OrdenPago, pk=pk)
		form = OrdenPagoEditarThirdForm(instance=p)
	return render(request, 'orden_pago/ordenpago_editar_2.html', {'form': form})

def orden_pago_editarPGDO(request, pk):
	if(request.method == 'POST'):
		p = get_object_or_404(OrdenPago, pk=pk)
		form = OrdenPagoEditarFinalForm(request.POST, instance=p)
		if(form.is_valid()):
			form.save()
			return redirect('orden_pago_lista')
	else:
		p = get_object_or_404(OrdenPago, pk=pk)
		form = OrdenPagoEditarFinalForm(instance=p)
	return render(request, 'orden_pago/ordenpago_editar_2.html', {'form': form, "p":p})


def orden_pago_enviar(request, pk):
	p = get_object_or_404(OrdenPago, cod_ord_pago=pk)
	p.estado = 'ENVD'
	p.save()
	return redirect('orden_pago_lista')


def orden_pago_autorizar(request, pk):
	p = get_object_or_404(OrdenPago, cod_ord_pago=pk)
	p.estado = 'AUTR'
	p.save()
	return redirect('pendiente_aprobacion')


def orden_pago_anular(request, pk=None):
	if(request.method == "POST"):
		p = get_object_or_404(OrdenPago, pk=pk)
		form = OrdenPagoForm(request.POST,instance=p)
		if(form.is_valid()):
			form.instance.estado = 'ANLD'
			form.save()
		return redirect('orden_pago_lista')
	else:
		pk = request.GET.get('pk')
		p = get_object_or_404(OrdenPago, pk=pk)
		form = OrdenPagoForm(instance=p)
		return render(request, 'orden_pago/ordenpago_anular.html', {'object':p, 'form':form})

financiero/orden_pago/templates/orden_pago/codigo.html
<input value="{{ codigo }}">

financiero/orden_pago/templates/orden_pago/dropdown_egresos.html
<option value="">---------</option>
{% for egr in egresos %}
<option value="{{ egr.pk }}">{{ egr.nombre }}</option>
{% endfor %}

financiero/orden_pago/templates/orden_pago/dropdown_juridica.html
<option value="">---------</option>
{% for empresa in proveedor %}
<option value="{{ empresa.pk }}">{{ empresa.ruc }} - {{ empresa.nombre }}</option>
{% endfor %}

financiero/orden_pago/templates/orden_pago/dropdown_naturales.html
<option value="">---------</option>
{% for persona in proveedor %}
<option value="{{ persona.cedula }}">{{ persona.cedula }} - {{ persona.nombres }} {{ persona.apellidos }}</option>
{% endfor %}

financiero/orden_pago/templates/orden_pago/ordenpago_anular.html
{% load crispy_forms_tags %}

<div class="row justify-content-md-center mt-5">
    <form method="post" action="{% url 'orden_pago_anular' object.id %}">
        {% csrf_token %}
        <h4>¿Está seguro que desea anular la siguiente orden de pago?</h4>
        <h4>Código: {{ object.cod_ord_pago }}</h4>

        {% for field in form %}

        {{ field.as_hidden }}
        {% endfor %}
        {{ form.motivo_anular|as_crispy_field }}
        <div class="col">
            <div class="row justify-content-center">
                <a href='javascript:;' onclick='cerrar(event);' class="btn btn-secondary"> Cancelar </a>
                <button class="btn btn-secondary green-bg mr-3" type="submit" onclick="close_form(event)"> Confirmar
                </button>
            </div>
        </div>
    </form>
</div>

<script>function close_form(e) {
        var modal = document.getElementById("myModal");
        modal.style.display = "block";
        modal.style.display = "none";
    }</script>

financiero/orden_pago/templates/orden_pago/ordenpago_autorizar.html
{% extends "base_financiero.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% load staticfiles %}
{% block title %}{{ "EC - Orden de pago" }}{% endblock %}

{% block content %}

<form method="POST" id="ordenPagoForm" data-egresos-url="{% url 'ajax_load_egresos' %}"
	data-proveedor-url="{% url 'ajax_load_proveedor' %}" novalidate>
	{% csrf_token %}
	<div class="row mb-2">
		<div class="col">
			<h2 class="text-uppercase ">Autorizar <span class="darkgreen-text">Orden de Pago</span></h2>
		</div>
	</div>
	<div class="row darkwhite-bg py-2">
		<div class="col-12">
			<div class="form-row">
				<div class="col-5"></div>
				<div class="col-5"></div>
				<div class="col-2">
					{{ form.estado|as_crispy_field }}
				</div>
			</div>
			<div class="form-row">
				<div class="col-4 col-xl-4">
					{{ form.cod_ord_pago|as_crispy_field }}
				</div>
				<div class="col-4 col-xl-4">
					{{ form.fecha|as_crispy_field }}
				</div>
			</div>
			<div class="form-row">
				<input type="hidden" name="tipo_proveedor" value='{{form.tipo_proveedor.value}}' />
				<div class="col-3 col-xl-3">
					{{ form.tipo_proveedor|as_crispy_field }}
				</div>
				<input type="hidden" name="proveedor" value='{{form.proveedor.value}}' />
				<div class="col-9 col-xl-6" id="field-proveedor">
					<div id="div_id_ruc_ci" class="form-group">
						<label for="{{ form.proveedor.id_for_label }}" class="col-form-label requiredField"
							id="ruc_ci">Razón social/Nombre</label><span class="asteriskField">*</span>
						<div>
							{{ form.proveedor}}
							{% if form.proveedor.errors %}
							{% for error in form.proveedor.errors %}
							<p class="invalid-feedback d-block">
								<strong>{{ error }}</strong>
							</p>
							{% endfor %}
							{% endif %}

						</div>
					</div>
				</div>
				<input type="hidden" id='rn' value="{{ form.proveedor.value }}">
			</div>
			<div class="form-row">
				<input type="hidden" name="centro_costos" value='{{form.centro_costos.value}}' />
				<div class="col-3 col-xl-3">
					{{ form.centro_costos|as_crispy_field }}
				</div>
				<input type="hidden" name="egreso" value='{{form.egreso.value}}' />
				<div class="col-9 col-xl-9">
					{{ form.egreso|as_crispy_field }}
				</div>
			</div>
			<div class="form-row">
				<input type="hidden" name="tipo_comprobante" value='{{form.tipo_comprobante.value}}' />
				<div class="col-4 col-xl-4">
					{{ form.tipo_comprobante|as_crispy_field }}
				</div>
				<div class="col-4 col-xl-4">
					{{ form.n_comprobante|as_crispy_field }}
				</div>
				<input type="hidden" name="forma_pago" value='{{form.forma_pago.value}}' />
				<div class="col-4 col-xl-4">
					{{ form.forma_pago|as_crispy_field }}
				</div>
			</div>
			<div class="form-row">
				<div class="col-12 col-xl-12">
					{{ form.concepto|as_crispy_field }}
				</div>
			</div>
			<div class="form-row">
				<div class="col-12 col-xl-12">
					{{ form.observacion|as_crispy_field }}
				</div>
			</div>
		</div>
	</div>
	<div class="row mt-3">
		<div class="mt-2 campo p-2 pl-3 col-12">
			<h5 class="black-text text-uppercase mb-0">Autorizar orden de pago</h5>
		</div>
	</div>
	<div class="row">
		<div class="col-12">
			<button type="submit" class="btn btn-secondary">Guardar</button>
			<a class="btn btn-light" href="{% url 'pendiente_aprobacion' %}"> Cancelar </a>
			<a href='javascript:;' onclick='anular({{ p.id }});' class="btn btn-secondary float-right">Anular</a>
			{% if form.estado.value != 'AUTR' and form.estado.value != 'ANLD' %}
			<a class="btn btn-success float-right mr-2"
				href="{% url 'orden_pago_autorizar' form.cod_ord_pago.value %}">Autorizar</a>
			{% endif %}
		</div>
	</div>
	{{ form.media }}
	<div id="myModal" class="modal">
		<div class="modal-content">
		  <span class="close">&times;</span>
		  <div id="modal-form">
		  </div>
		</div>
	</div>
</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
<script src="{% static 'js/orden_pago.js' %}"></script>

<script type="text/javascript">
	window.onload = function () {
		document.getElementById("id_cod_ord_pago").readOnly = true;
		document.getElementById("id_estado").disabled = true;
	};

	$("#id_centro_costos").change(function () {
		var url = $("#ordenPagoForm").attr("data-egresos-url");
		var ccId = $(this).val();
		$.ajax({
			url: url,
			data: {
				'centro_costos': ccId
			},
			success: function (data) {
				$("#id_egreso").html(data);
			}
		});
	});

	function anular(id){
  		var modal = document.getElementById("myModal");
  		modal.style.display = "block";

		var span = document.getElementsByClassName("close")[0];


		span.onclick = function() {
			modal.style.display = "none";
		}

		// When the user clicks anywhere outside of the modal, close it
		window.onclick = function(event) {
			if (event.target == modal) {
				modal.style.display = "none";
			}
		}

		$.ajax({
			url: "{% url 'orden_pago_anular' %}",  
			data:{
				"pk": id
			}, 
			success: function (data) {   
				$("#modal-form").html(data);  
			}
		});
	}

	function cerrar(e){
		var modal = document.getElementById("myModal");
  		modal.style.display = "block";
		modal.style.display = "none";
	}

</script>
{% endblock %}

financiero/orden_pago/templates/orden_pago/ordenpago_editar_2.html
{% extends "base_financiero.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% load staticfiles %}
{% block title %}{{ "EC - Orden de pago" }}{% endblock %}

{% block content %}

<form method="POST" novalidate id="ordenPagoForm" enctype="multipart/form-data" data-egresos-url="{% url 'ajax_load_egresos' %}"
	data-proveedor-url="{% url 'ajax_load_proveedor' %}"  >
	{% csrf_token %}
	<div class="row mb-2">
		<div class="col">
			<h2 class="text-uppercase darkgreen-text">Edición Orden de Pago</h2>
		</div>
	</div>
	<div class="row darkwhite-bg py-2">
		<div class="col-12">
			<div class="form-row">
				<input type="hidden" name="estado" value='{{form.estado.value}}' />
				<div class="col-3">
					{{ form.estado|as_crispy_field }}
				</div>
				<div class="col-4 col-xl-3">
					{{ form.cod_ord_pago|as_crispy_field }}
				</div>
				<div class="col-4 col-xl-3">
					{{ form.n_tramite|as_crispy_field }}
				</div>
				
			</div>
			<div class="form-row">
				<div class="col-4 col-xl-3">
					{{ form.fecha|as_crispy_field }}
				</div>
				<div class="col-4 col-xl-3">
					{{ form.fecha_tramite|as_crispy_field }}
				</div>
				<div class="col-4 col-xl-3">
					{{ form.fecha_pago|as_crispy_field }}
				</div>
			</div>
			<div class="form-row">
                <input type="hidden" name="tipo_proveedor" value='{{form.tipo_proveedor.value}}' />
				<div class="col-3 col-xl-3">
					{{ form.tipo_proveedor|as_crispy_field }}
                </div>
				<input type="hidden" name="proveedor" value='{{form.proveedor.value}}' />
				<div class="col-8 col-xl-6" id="field-proveedor">
					<div id="div_id_ruc_ci" class="form-group">
						<label for="{{ form.proveedor.id_for_label }}" class="col-form-label requiredField"
							id="ruc_ci">Razón
							social/Nombre</label><span class="asteriskField">*</span>
						<div>
							{{ form.proveedor}}
							{% if form.proveedor.errors %}
							{% for error in form.proveedor.errors %}
							<p class="invalid-feedback d-block">
								<strong>{{ error }}</strong>
							</p>
							{% endfor %}
							{% endif %}

						</div>
					</div>
				</div>
				<input type="hidden" id='rn' value="{{ form.proveedor.value }}">
			</div>
			<div class="form-row">
				<input type="hidden" name="centro_costos" value='{{form.centro_costos.value}}' />
				<div class="col-3 col-xl-3">
					{{ form.centro_costos|as_crispy_field }}
				</div>
				<input type="hidden" name="egreso" value='{{form.egreso.value}}' />
				<div class="col-9 col-xl-6">
					{{ form.egreso|as_crispy_field }}
				</div>
			</div>
			<div class="form-row">
				<input type="hidden" name="tipo_comprobante" value='{{form.tipo_comprobante.value}}' />
				<div class="col-4 col-xl-4">
					{{ form.tipo_comprobante|as_crispy_field }}
				</div>
				<div class="col-4 col-xl-4">
					{{ form.n_comprobante|as_crispy_field }}
				</div>
				<input type="hidden" name="forma_pago" value='{{form.forma_pago.value}}' />
				<div class="col-4 col-xl-4">
					{{ form.forma_pago|as_crispy_field }}
				</div>
			</div>
			<div class="form-row">
				<div class="col-12 col-xl-6">
					{{ form.documentos|as_crispy_field }}
				</div>
				<div id="div_id_anexo" class="form-group">
					<label for="id_anexo" class="col-form-label requiredField">
						Anexo<span class="asteriskField">*</span>
					</label>
					<div class="">
						{% if form.anexo.value %}
						<a class="btn btn-secondary btn-sm" href="{{form.anexo.value.url}}" target="_blank">
							Descargar
						</a>
						{% else %}
						{{form.anexo}}
						{% endif %}
					</div>
				</div>
			</div>
			<div class="form-row">
				<div class="col-12 col-xl-6">
					{{ form.concepto|as_crispy_field }}
				</div>
				<div class="col-12 col-xl-6">
					{{ form.observacion|as_crispy_field }}
				</div>
			</div>
		</div>
	</div>
	{% if messages %}
    {% for message in messages %}
      <div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %}">{{ message|safe }}</div>
    {% endfor %}
  {% endif %}

  {% if form.errors %}
    <div class="alert alert-error">
      <h4>Please fix the following errors</h4>
      <ul>
        {% for field in form %}
          {% if field.errors %}
            {% for error in field.errors %}
              <li><a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a></li>
            {% endfor %}
          {% endif %}
        {% endfor %}
      </ul>
      {% if form.non_field_errors %}
        {{ form.non_field_errors }}
      {% endif %}
    </div>
  {% endif %}
	<div class="row mt-3">
		<div class="col-12">
			<button type="submit" class="btn btn-secondary green-bg">Guardar</button>
			<a class="btn btn-secondary" href="{% url 'orden_pago_lista' %}"> Cancelar </a>
		</div>
		
	</div>
	{{ form.media }}
</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
<script src="{% static 'js/orden_pago.js' %}"></script>

<script type="text/javascript">
	window.onload = function () {
		document.getElementById("id_cod_ord_pago").readOnly = true;
		document.getElementById("id_estado").disabled = true;
	};

	$("#id_centro_costos").change(function () {
		var url = $("#ordenPagoForm").attr("data-egresos-url");
		var ccId = $(this).val();
		$.ajax({
			url: url,
			data: {
				'centro_costos': ccId
			},
			success: function (data) {
				$("#id_egreso").html(data);
			}
		});
	});

</script>
{% endblock %}