educacion_continua2/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('administrativo/proveedores/', include("administrativo.proveedores.urls")),
	path('ventas/personas_juridicas/', include("ventas.personas_juridicas.urls")),
	path('ventas/reporte_contacto/', include("ventas.reporte_contacto.urls")),
    path('ventas/personas_naturales/', include("ventas.personas_naturales.urls")),
    path('ventas/propuesta_corp/', include("ventas.propuesta_corp.urls")),
    path('ventas/proformas/',include("ventas.proformas.urls")),
    path('ventas/interesados/',include("ventas.interesados.urls")),
    path('financiero/perfiles/', include('financiero.perfiles.urls')),
    path('financiero/orden_Ingreso/',include('financiero.orden_ingreso.urls')),
    path('financiero/orden_facturacion/',include('financiero.orden_facturacion.urls')),
    path("financiero/presupuestos/",include("financiero.presupuestos.urls")),
    path("financiero/orden_pago/",include("financiero.orden_pago.urls")),
    path("financiero/pago_eventos/",include("financiero.pago_eventos.urls")),
    path("financiero/presupuestos_anuales/",include("financiero.presupuestos_anuales.urls")),
    path("financiero/plan_anual_compras/",include("financiero.plan_anual_compras.urls")),
    path("financiero/procesos_especiales/",include("financiero.procesos_especiales.urls")),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

financiero/orden_ingreso/urls.py
from django.urls import path
from django_filters.views import FilterView
from . import views
from .filters import OrdenIngresoFilter
from .models import OrdenIngreso
from itertools import chain


final =  OrdenIngreso.objects.order_by('cod_orden_ing')



urlpatterns = [
    path('nuevo', views.OrdenIngresoCreate.as_view(), name='ordenIngreso_nuevo'),
    path('ajax_orden_facturacion/', views.load_orden_facturacion, name='ajax_orden_facturacion'),
    path('nuevo/<pk>/', views.OrdenIngresoCreate.as_view(), name='ordenIngreso_nuevo'),
    path('', FilterView.as_view(filterset_class=OrdenIngresoFilter,template_name="ordenIngreso_list.html",queryset=final), name='ordenIngreso'),
    path('editar/<pk>/', views.OrdenIngresoUpdate.as_view(), name='ordenIngreso_editar'),
    path('imprimir/<pk>/', views.OrdenIngresoPrint.as_view(), name='ordenIngreso_print'),        
    path('eliminar/<pk>/', views.OrdenIngresoDelete.as_view(), name='ordenIngreso_eliminar'),
    path('ajax/load-modal-orden-ing',views.orden_ing_conf_elim,name='orden_ingreso_confirmar_eliminar'),
]

financiero/orden_ingreso/models.py
from django.db import models
from financiero.orden_facturacion.models import OrdenFacturacion
import financiero.validaciones as val_fin
from financiero.orden_facturacion.models import Centro_Costos
# Create your models here.
class OrdenIngreso(models.Model):
	class Meta:
		ordering = ['-cod_orden_ing']

	FORMAS_PAGO=[
		("Cheque","Cheque"),
		("Transferencia","Transferencia"),
		("Depósito","Depósito"),
		("Tarjeta de Crédito","Tarjeta de Crédito"),
	]
	TARJETAS=[
		("Visa","Visa"),
		("Mastercard","Mastercard"),
		("American Express","American Express"),
		("Diners","Diners"),
		("Discover","Discover"),
	]
	TIPO_CHOICES=[('Natural','Natural'),('Jurídica','Jurídica'),]
	ESTADO_CHOICES = [  
        ('ACTV','Activa'),
        ('ANLD','Anulada'),
	]

	
	cod_orden_ing=models.CharField(max_length=15, blank=True)
	tipo_cliente=models.CharField(max_length=15, choices=TIPO_CHOICES)
	fecha=models.DateField(blank=True, null=True)
	n_tramite=models.CharField(max_length=15,blank=True, null=True, default='No asignado')

	fecha_tramite=models.DateField(blank=True, null=True,verbose_name="Fecha trámite")
	fecha_anulacion=models.DateField(blank=True, null=True, verbose_name="")
	estado = models.CharField(max_length=5,default='ACTV',choices=ESTADO_CHOICES, blank=True, null=True,verbose_name="Estado Orden Ingreso")
	saldo_facturacion=models.DecimalField(max_digits=10,decimal_places=2,validators=[val_fin.validate_positivo], blank=True, null=True,default=0)
	centro_costos = models.ForeignKey(Centro_Costos, on_delete=models.SET_NULL, blank=False, null=True)


	n_factura=models.CharField(max_length=15,blank=True, null=True, default='No asignado')
	ruc_ci=models.CharField(max_length=13)

	orden_facturacion = models.ForeignKey(OrdenFacturacion, on_delete=models.SET_NULL, blank=False, null=True)
	
	razon_nombres=models.CharField(max_length=50)
	descripcion=models.CharField(max_length=150)
	formaPago=models.CharField(max_length=30, choices=FORMAS_PAGO,default='cheque')
	# valor=models.DecimalField(max_digits=15,decimal_places=2,validators=[val_fin.validate_positivo])
	valor=models.FloatField(blank=True, null=True,default=0.0,validators=[val_fin.validate_positivo])
	
	fechaPago=models.CharField(max_length=12)
	numeroDocumento=models.PositiveIntegerField()
	banco=models.CharField(max_length=30)
	emisoraTarjeta=models.CharField(max_length=20,choices=TARJETAS, blank=True)
	# def formfield_for_foreignKey(self,db_field,request, **kwargs):
	# 	if db_field.name == "orden_facturacion":
	# 		kwargs["queryset"]= OrdenFacturacion.objects.filter(estado="PNDP")
	# 	return super(OrdenIngreso,self).formfield_for_foreignkey(self,db_field,request, **kwargs)


	def delete(self, *arg, **kwargs):
		
		super().delete(*arg,**kwargs)

class OrdenIngresoFile(models.Model):
    file = models.FileField(upload_to='uploads/OrdenIngreso/',blank=True, null=True)
    #file = models.CharField(max_length=50, blank=True,default=" ")
    #propuesta = models.ManyToManyField(PropuestaCorporativo, through='PropFileKey')
    orden=models.ForeignKey(OrdenIngreso, on_delete=models.CASCADE)

financiero/orden_ingreso/forms.py
from django import forms
from .models import OrdenIngreso, OrdenIngresoFile
from financiero.orden_facturacion.models import OrdenFacturacion
from datetime import date
from django.core.exceptions import ObjectDoesNotExist
from django.forms.models import inlineformset_factory

class OrdenIngresoForm(forms.ModelForm):

	class Meta:
		model=OrdenIngreso
		fields='__all__'

		labels={
			'tipo_cliente':'Cliente',
			'fecha':'Fecha',
			'ruc_ci':'RUC',
			'razon_nombres':'Razón Social',
			'descripcion':'Descripción',
			'formaPago':'Forma de Pago',
			'valor':'Valor',
			'fechaPago':'Fecha Pago',
			'numeroDocumento':'N° Documento',
			'banco':"Banco",
			'emisoraTarjeta':"Emisora TC",
			'orden_facturacion':"Orden facturación",
		}

		widgets={
			'fecha':forms.DateInput(attrs={'class':'form-control','type':'date','value':date.today}),
			'fechaPago':forms.DateInput(attrs={'class':'form-control','type':'date','value':date.today}),
			'razon_nombres':forms.Select(attrs={'class':'form-control select2'}),
            'ruc_ci':forms.Select(attrs={'class':'form-control select2'}),
			'orden_facturacion':forms.Select(attrs={'class':'form-control select2'}),
			
			'descripcion':forms.Textarea(attrs={'rows':2}),
			'valor':forms.NumberInput(attrs={'class':'form-control'}),
			'numeroDocumento':forms.NumberInput(attrs={'class':'form-control'}),
			'banco':forms.TextInput(attrs={'class':'form-control'}),
			'emisoraTarjeta':forms.Select(attrs={'class':'select form-control'}),
			'formaPago':forms.Select(attrs={'id':'seleccion',"onchange":"run()"})
		}
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['orden_facturacion'].queryset = OrdenFacturacion.objects.filter(estado="PNDP")
		
	

	def genera_codigo(self):
		sec = "vacio"
		try:
			pre=str(int(self.Meta.model.objects.latest('pk').pk+1))
			sec='0'*(4-len(pre))+pre
		except ObjectDoesNotExist :
			sec='0001'
		print(sec)
		self.instance.cod_orden_ing= sec +'-'+str(date.today().year)

	def clean(self):
		
		cd = self.cleaned_data
		try:
			if(cd.get('valor')==None):
				self.add_error('valor', 'Valor excede máxima cantidad soportada')
			elif ((cd.get('orden_facturacion').valor_pendiente - cd.get('valor')) <0) :
				self.add_error('valor', 'El valor a pagar excede el valor pendiente de la orden de facturación, pendiente: $'+str(cd.get('orden_facturacion').valor_pendiente))
			return cd
		except :
			self.add_error('orden_facturacion',"El campo de orden de facturación no puede ser vacío")	

		

		
		# if(cd['valor']==None):
		# 	raise forms.ValidationError('Valor excede máxima cantidad soportada')
		# elif (cd['orden_facturacion'].valor_pendiente - cd.get('valor') <0):
		# 	raise forms.ValidationError('El valor a pagar excede el valor pendiente de la orden de facturación, pendiente: $'+str(cd.get('orden_facturacion').valor_pendiente))
		# else:
		# 	return cd['valor']

class OrdenIngresoUpdateForm(forms.ModelForm):
	def __init__(self, *args, **kwargs):
		super(OrdenIngresoUpdateForm, self).__init__(*args, **kwargs)
		self.fields['orden_facturacion'].disabled = True
		self.fields['centro_costos'].disabled = True
		
	class Meta:
		model=OrdenIngreso
		fields='__all__'

		labels={
			'cod_orden_ing': 'Código Orden Ingreso',
			'tipo_cliente':'Cliente',
			'fecha':'Fecha',
			'n_tramite':'N° de Trámite',
			'ruc_ci':'RUC',
			'razon_nombres':'Razón Social',
			'descripcion':'Descripción',
			'formaPago':'Forma de Pago',
			'valor':'Valor',
			'fechaPago':'Fecha Pago',
			'numeroDocumento':'N° Documento',
			'banco':"Banco",
			'emisoraTarjeta':"Emisora TC",
			'pk':'id',
		}

		widgets={
			'cod_orden_ing':forms.TextInput(attrs={'readonly':True,'class':'form-control-plaintext'}),
			'fecha':forms.DateInput(attrs={'readonly':True,'class':'form-control-plaintext','type':'date','value':date.today}),
			'fechaPago':forms.DateInput(attrs={'readonly':True,'class':'form-control-plaintext','type':'date','value':date.today}),
			
			'n_tramite':forms.TextInput(attrs={'class':'form-control'}),
			'fecha_tramite':forms.DateInput(attrs={'class':'form-control','type':'date'}),
			'estado':forms.HiddenInput(),
			



			'fechaPago':forms.DateInput(attrs={'class':'form-control','type':'date'}),
			 
			'tipo_cliente':forms.TextInput(attrs={'readonly':True,'class':'form-control-plaintext'}),
			'razon_nombres':forms.TextInput(attrs={'readonly':True,'class':'form-control-plaintext form-control'}),
            'ruc_ci':forms.TextInput(attrs={'readonly':True,'class':'form-control-plaintext form-control'}),
			'descripcion':forms.Textarea(attrs={'readonly':True,'rows':2,'class':'form-control-plaintext'}),
			'valor':forms.NumberInput(attrs={'readonly':True,'class':'form-control-plaintext'}),
			'numeroDocumento':forms.NumberInput(attrs={'readonly':True,'class':'form-control-plaintext form-control'}),
			'banco':forms.TextInput(attrs={'readonly':True,'class':'form-control-plaintext'}),
			'emisoraTarjeta':forms.TextInput(attrs={'readonly':True,'class':'select form-control-plaintext textinput textInput form-control'}),
			'formaPago':forms.TextInput(attrs={'readonly':True,'id':'seleccion'}),
		}
class OrdenIngresoPrintForm(forms.ModelForm):

	class Meta:
		model=OrdenIngreso
		fields='__all__'

		labels={
			'cod_orden_ing': 'Código',
			'tipo_cliente':'Cliente',
			'fecha':'Fecha',
			'n_tramite':'N° de Trámite',
			'ruc_ci':'RUC',
			'razon_nombres':'Razón Social',
			'descripcion':'Descripción',
			'formaPago':'Forma de Pago',
			'valor':'Valor',
			'fechaPago':'Fecha Pago',
			'numeroDocumento':'N° Documento',
			'banco':"Banco",
			'emisoraTarjeta':"Emisora TC",
		}

		widgets={
			'cod_orden_ing':forms.TextInput(attrs={'readonly':True,'class':'form-control-plaintext'}),
			'fecha':forms.DateInput(attrs={'readonly':True,'class':'form-control-plaintext','type':'date','value':date.today}),
			'fechaPago':forms.DateInput(attrs={'readonly':True,'class':'form-control-plaintext','type':'date','value':date.today}),
			'n_tramite':forms.TextInput(attrs={'readonly':True, 'class':'form-control'}),
			'tipo_cliente':forms.TextInput(attrs={'readonly':True,'class':'form-control-plaintext'}),
			'razon_nombres':forms.TextInput(attrs={'readonly':True,'class':'form-control-plaintext form-control'}),
            'ruc_ci':forms.TextInput(attrs={'readonly':True,'class':'form-control-plaintext form-control'}),
			'descripcion':forms.Textarea(attrs={'readonly':True,'rows':2,'class':'form-control-plaintext'}),
			'valor':forms.NumberInput(attrs={'readonly':True,'class':'form-control-plaintext'}),
			'numeroDocumento':forms.NumberInput(attrs={'readonly':True,'class':'form-control-plaintext form-control'}),
			'banco':forms.TextInput(attrs={'readonly':True,'class':'form-control-plaintext'}),
			'emisoraTarjeta':forms.TextInput(attrs={'readonly':True,'class':'select form-control-plaintext textinput textInput form-control'}),
			'formaPago':forms.TextInput(attrs={'readonly':True,'id':'seleccion'})
		}

class FileForm(forms.ModelForm):

    class Meta: 
        model= OrdenIngresoFile 
        exclude=()

FileFormset = inlineformset_factory(
    OrdenIngreso, OrdenIngresoFile, form=FileForm,
    fields=['file'],widgets={"file":forms.ClearableFileInput(attrs={'class':'ingresof','accept':'.pdf'})},
     extra=1,can_delete=True
    )

financiero/orden_ingreso/views.py
from django.shortcuts import render
from django.template.loader import render_to_string
from django.http import HttpResponseRedirect,JsonResponse
from django.views.generic import CreateView,UpdateView,DeleteView
from .models import OrdenIngreso
from .forms import OrdenIngresoForm, OrdenIngresoUpdateForm, OrdenIngresoPrintForm, FileFormset
from django.urls import reverse_lazy
from datetime import date,datetime
from financiero.orden_facturacion.models import OrdenFacturacion
from django.db import transaction
# Create your views here.



class OrdenIngresoCreate(CreateView):
    model=OrdenIngreso
    form_class=OrdenIngresoForm
    template_name='ordenIngreso_form.html'
    success_url=reverse_lazy('ordenIngreso')
    def get_initial(self):
        initial = super(OrdenIngresoCreate, self).get_initial()
        # Copy the dictionary so we don't accidentally change a mutable dict
        initial = initial.copy()
        try:
            datos = OrdenFacturacion.objects.get(pk=self.kwargs.get('pk'))
            
            if(datos!=None):
                initial["ruc_ci"]=datos.ruc_ci
                initial["orden_facturacion"] = datos.id
                initial["tipo_cliente"]="Natural"
        except:
            pass
        return initial
    
    def get_context_data(self, **kwargs):
        context=super(OrdenIngresoCreate,self).get_context_data(**kwargs)
        context['formset'] = FileFormset()
        return context
        
    def post(self, request,*args,**kwargs):
        self.object =self.get_object
        form=self.form_class(request.POST)
        if form.is_valid():
            obj=(form.instance.orden_facturacion)
            obj.valor_pendiente-=form.instance.valor;
            print(obj)
            print(obj.valor_pendiente)
            if(obj.valor_pendiente==0):
                obj.estado='CNCL'
            obj.save()
            self.form_class.genera_codigo(form)
            form.instance.saldo_facturacion = obj.valor_pendiente
            self.object = form.save()
            
            titles = FileFormset(self.request.POST,self.request.FILES)
            if titles.is_valid():
                
                
                titles.instance = self.object
                titles.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form))
            
    # def get_success_url(self, **kwargs):         
    #         return reverse_lazy('ordenIngreso')
   
        

class OrdenIngresoUpdate(UpdateView):
    
    model=OrdenIngreso
    form_class=OrdenIngresoUpdateForm
    template_name='ordenIngreso_editar.html'
    success_url=reverse_lazy('ordenIngreso')
    def get_context_data(self, **kwargs):
        context = super(OrdenIngresoUpdate, self).get_context_data(**kwargs)
        context['pk'] = self.kwargs['pk']
        if self.request.POST:
            context['formset'] = FileFormset(self.request.POST,self.request.FILES, instance=self.object)
            print("No hiciste el anular, entraste a actualizar")
        else:
            context['formset'] =FileFormset(instance=self.object)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        titles = context['formset']
        with transaction.atomic():
            form.instance.created_by = self.request.user
            self.object = form.save()
            if titles.is_valid():
                titles.instance = self.object
                titles.save()
        return super(OrdenIngresoUpdate, self).form_valid(form)
    

class OrdenIngresoPrint(UpdateView):
    model=OrdenIngreso
    form_class=OrdenIngresoPrintForm
    template_name='ordenIngreso_print.html'
    success_url=reverse_lazy('ordenIngreso')

class OrdenIngresoDelete(DeleteView):
    model=OrdenIngreso
    template_name='ordenIngreso_eliminar.html'
    success_url=reverse_lazy('ordenIngreso')
    def post(self, request, *args, **kwargs):
        self.object=self.get_object()
        self.object.estado="ANLD" 
        self.object.fecha_anulacion = datetime.now().strftime('%Y-%m-%d')
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())
    

def orden_ing_conf_elim(request):
    orden_id=request.GET.get('pk')

    print(orden_id)
    orden=OrdenIngreso.objects.get(id=orden_id)

    print(orden)
    return render(request,"ordenIngreso_eliminar.html",{"ordenIngreso":orden})

def load_orden_facturacion(request):
    ordenes = OrdenFacturacion.objects.all()
    opciones=render_to_string("dropdown_orden_facturacion.html",{"orden_facturacion":ordenes})
    print(opciones)
    return JsonResponse({'ordenes_facturacion': opciones})
        

financiero/orden_ingreso/templates/ordenIngreso_editar.html
{% extends 'base_financiero.html' %}
{% load static %}

{% load crispy_forms_tags %}
{% load index %}

{% block title %}{{ "EC - Orden de Ingreso" }}{% endblock title %}

{% block extraheader %}
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
{% endblock extraheader %}

{% block content %}
<form method="POST" novalidate id="form-fact" enctype="multipart/form-data" ,
	data-persona-url="{% url 'ajax_load_personas' %}">
	{% csrf_token %}
	<div class="row mb-2">
		<div class="col-12">
			<h2 class="text-uppercase darkgreen-text">edición Orden de Ingreso  <strong class="black-text font-weight-bold"> N° {{form.cod_orden_ing.value}}</strong></h2>
		</div>
	</div>
	<div class="row darkwhite-bg py-2">
		<div class="col-12">
			<div class="form-row">
				{{form.estado}}
				<div class="col-3">
					{{form.cod_orden_ing|as_crispy_field}}
				</div>
				<div class="col-3">
					{{form.n_tramite|as_crispy_field}}
				</div>
				<div class="col-3">
					{{form.fecha_tramite|as_crispy_field}}
				</div>
				
				
			</div>
			<div class="form-row">
				<div class="col-6 col-md-3 mb-0">
					{{form.tipo_cliente|as_crispy_field}}
					<small class="form-text text-muted">Seleccione el tipo de cliente</small>
				</div>
				<div class="col-6 col-md-3 mb-0">
					{{ form.fecha|as_crispy_field }}
				</div>
				<div class="col-6 col-md-3 mb-0 " id="field-ruc-ci">
					<div id="div_id_ruc_ci" class="form-group">
						<label for="{{ form.ruc_ci.id_for_label}}" class="col-form-label requiredField"
							id="ruc_ci">RUC/CI</label><span class="asteriskField">*</span>
						<div>
							{{ form.ruc_ci}}
							{% if form.ruc_ci.errors %}
							{% for error in form.ruc_ci.errors %}
							<p class="invalid-feedback d-block">
								<strong>{{ error }}</strong>
							</p>
							{% endfor %}
							{% endif %}
						</div>
					</div>
				</div>
				<div class="col-6 col-md-3 mb-0 " id="field-razon">
					<div id="div_id_razon_nombres" class="form-group">
						<label for="{{ form.razon_nombres.id_for_label}}" class="col-form-label requiredField"
							id="ra_nom">Razón
							Social/Nombres</label><span class="asteriskField">*</span>
						<div>

							{{ form.razon_nombres}}
							{% if form.razon_nombres.errors %}
							{% for error in form.razon_nombres.errors %}
							<p class="invalid-feedback d-block">
								<strong>{{ error }}</strong>
							</p>
							{% endfor %}
							{% endif %}

						</div>
					</div>
				</div>
				<input type="hidden" id='rc' value="{{form.ruc_ci.value}}">
				<input type="hidden" id='rn' value="{{form.razon_nombres.value}}">
			</div>
			<div class="form-row">
				<div class="col-12">
					{{form.orden_facturacion|as_crispy_field}}
				</div>
			</div>
			<div class="row">
				<div class="col-8">
					{{form.descripcion|as_crispy_field}}
				</div>
				<div class="col-4">
					{{form.centro_costos|as_crispy_field}}
				</div>
			</div>
			<div class="mt-2 campo p-2">
				<h2 class="black-text text-uppercase">Detalle del Pago</h2>
			</div>
			<div class="row">
				<div class="col-4">
					{{form.formaPago|as_crispy_field}}
				</div>
				<div class="col-4">
					{{form.fechaPago|as_crispy_field}}
				</div>
				<div class="col-2">
					{{form.numeroDocumento|as_crispy_field}}
				</div>
			</div>
			<div class="row">
				
				<div class="col-6">
					{{form.banco|as_crispy_field}}
				</div>
				<div class="col-3">
					<label for="{{ form.emisoraTarjeta.id_for_label}}" class="col-form-label"
						id="id_emisoraTarjeta">Emisora
						TC</label><span class="asteriskField" id="asterisco">*</span>
					{{form.emisoraTarjeta}}
					<small class="form-text text-muted">Obligatorio con Tarjeta de Crédito</small>
				</div>
				<div class="col-3">
					{{form.valor|as_crispy_field}}
				</div>
			</div>
			<div class="row">
				<div class="col-xl-12">
					<table id="tablefile" class="table table-responsive-md border-bottom">
						{{ formset.management_form|crispy }}
						
							{% for form in formset.forms %}
									<tr class="{% cycle 'row1' 'row2' %} form-control prueba form-row formset_row-{{ formset.prefix }}">
										{% for field in form.visible_fields %}
										<td scope="row">
											{# Include the hidden fields in the form #}
											{% if forloop.first %}
												{% for hidden in form.hidden_fields %}
													{{ hidden }}
												{% endfor %}
											{% endif %}
											{{ field.errors.as_ul }}
											{{ field|as_crispy_field }}
										</td>
										{% endfor %}
									</tr>
							{% endfor %}
						
						</table>
				</div>

			</div>
		</div>
	</div>
	<div id="row-botones" class="row  d-flex">
		<div>
				<button id ="guardar_orden_ingreso" type="submit" class="btn btn-secondary green-bg ml-3 ">Guardar</button>
				<a class="btn btn-secondary ml-sm-2" href="{% url 'ordenIngreso' %}"> Cancelar </a>	
		</div>
		 <div class="offset-5 offset-sm-6 offset-xl-9 text-center ml-auto mr-3">
			<a id = "anular_orden_ingreso" onclick='eliminar({{ pk }});' class="btn  btn-secondary"
					data-toggle='modal' data-target="#ordenEliminarCenter" href='#'> Anular
				</a> 
			
		</div> 
		 {% comment %} <div class="col-4 offset-sm-2 col-sm-3 offset-md-10 col-md-2 offset-lg-10 col-lg-2 offset-xl-7  col-xl-3">
			<div class="container-fluid">
				<div class = "row">
					<div class="col-12">
						<a id = "anular_orden_ingreso" onclick='eliminar({{ pk }});' class="btn  btn-secondary "
						data-toggle='modal' data-target="#ordenEliminarCenter" href='#'> Anular
						</a> 
					</div>
					
				</div>
			</div> 
		 </div> {% endcomment %}
			
			
		
		
	</div>

</div>
	
		
	
	
	<div class="modal fade" id="ordenEliminarCenter" tabindex="-1" role="dialog" aria-labelledby="ordenTitle"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
        </div>
    </div>
</div>
</form>

{% endblock %}
{% block extrafooter %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
<script src="{% static 'js/ordenIngreso_money.js' %}"></script>
<script src="{% static 'js/ordenIngreso_anulada.js' %}"></script>
<script src="{% static 'js/ingreso_file.js' %}"></script>
<script>
    function eliminar(id) {
        $.ajax({
            url: "{% url 'orden_ingreso_confirmar_eliminar' %}",
            data: {
                'pk': id
            },
            success: function (data) {
                $(".modal-content").html(data)
            }
        });
    };


</script>
{% endblock extrafooter %}

financiero/orden_ingreso/templates/ordenIngreso_eliminar.html
<div class="modal-header">
    <h5 class="modal-title" id="ordenTitle">Anulación de Orden de Ingreso {{ordenIngreso.cod_orden_ing}}</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<form method="POST" action="{% url 'ordenIngreso_eliminar' ordenIngreso.id %}">
    {% csrf_token %}

    <div class="modal-body">
        ¿Está seguro que desea anular la siguiente orden de ingreso?
        Código: {{ordenIngreso.cod_orden_ing}}
    </div>
    <div class="modal-footer">
        <button class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
        <button class="btn btn-secondary green-bg mr-3" type="submit"> Anular </button>
    </div>
</form>