educacion_continua2/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('administrativo/proveedores/', include("administrativo.proveedores.urls")),
	path('ventas/personas_juridicas/', include("ventas.personas_juridicas.urls")),
	path('ventas/reporte_contacto/', include("ventas.reporte_contacto.urls")),
    path('ventas/personas_naturales/', include("ventas.personas_naturales.urls")),
    path('ventas/propuesta_corp/', include("ventas.propuesta_corp.urls")),
    path('ventas/proformas/',include("ventas.proformas.urls")),
    path('ventas/interesados/',include("ventas.interesados.urls")),
    path('financiero/perfiles/', include('financiero.perfiles.urls')),
    path('financiero/orden_Ingreso/',include('financiero.orden_ingreso.urls')),
    path('financiero/orden_facturacion/',include('financiero.orden_facturacion.urls')),
    path("financiero/presupuestos/",include("financiero.presupuestos.urls")),
    path("financiero/orden_pago/",include("financiero.orden_pago.urls")),
    path("financiero/pago_eventos/",include("financiero.pago_eventos.urls")),
    path("financiero/presupuestos_anuales/",include("financiero.presupuestos_anuales.urls")),
    path("financiero/plan_anual_compras/",include("financiero.plan_anual_compras.urls")),
    path("financiero/procesos_especiales/",include("financiero.procesos_especiales.urls")),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

financiero/orden_facturacion/urls.py
from django.urls import path
from django_filters.views import FilterView
from financiero.orden_facturacion import views
from .filters import OrdenFacturacionFilter


urlpatterns = [
    path('nuevo', views.OrdenFacturacionCreate.as_view(), name='orden_facturacion_nuevo'),
    path('ajax/load-personas',views.load_personas,name='ajax_load_personas'),
    path('ajax/load-modal-orden-fact',views.orden_fact_conf_elim,name='orden_facturacion_confirmar_eliminar'),
    path('ajax/verificar-campos',views.verificar_campos,name='ajax_verificar_campos'),
    path('ajax/info-cliente',views.load_info,name='ajax_info_id'),
    path('ajax/info-cliente-veris',views.load_info_veris,name='ajax_info_veris_id'),
    path('ajax/load-contactos',views.load_contactos,name='ajax_load_contactos'),
    path('ajax/load-mail',views.load_mail,name='ajax_load_mail'),
    path('ajax/load-usuarios-ventas',views.load_usuarios_ventas,name='ajax_load_usuarios_ventas'),
    path('ajax/orden-ci',views.load_info_ci,name="ajax_orden_ci"),
    path('', views.index, name='orden_facturacion'),
    path('editar/<pk>/', views.OrdenFacturacionUpdate.as_view(), name='orden_facturacion_editar'),    
    path('eliminar/<pk>/', views.OrdenFacturacionDelete.as_view(), name='orden_facturacion_eliminar'),
    path('cambiar-estado/<pk>/', views.cambiar_estado, name='orden_facturacion_estado'),
    path('participante/nuevo/<pk>/',views.ParticipanteCreate.as_view(),name='participante_nuevo'),
    path('participante/editar/<pk>/<fk>/',views.ParticipanteUpdate.as_view(),name='participante_editar'),
    path('participante/eliminar/<pk>/<fk>/',views.ParticipanteDelete.as_view(),name='participante_eliminar'),
    path('ajax/confirmar-eliminar-par',views.participante_conf_elim,name='participante_confirmar_eliminar'),
    path('aprobar/<pk>',views.aprobar_orden_facturacion, name="orden_facturacion_aprobar"),
    path('anular/<pk>',views.anular_orden_facturacion, name="orden_facturacion_anular"),
    path('anularM/<pk>',views.anular_orden_facturacionMenu, name="orden_facturacion_anularMenu"),
]

financiero/orden_facturacion/models.py
from django.db import models
from ventas.personas_juridicas.models import Juridica, Contacto_natural
from ventas.personas_naturales.models import Persona_Natural

import ventas.validaciones as val
import financiero.validaciones as val_fin

from financiero.orden_pago.models import Centro_Costos
import ventas.validaciones



TIPO_EVENTO=[('Abierto','Abierto'),('Corporativo','Corporativo')]

# Create your models here.
ESTADO_CHOICES = [  
        ('ACTV','Grabado'),
        ('SLCE','Solicitud Enviada'),
	    ('ACPF', 'Autorizada por Financiero'),
        ('PNDP','Pendiente de Cobro'),
        ('CNCL','Cancelada'),
        ('ANLD','Anulada'),
	]

class OrdenFacturacion(models.Model):
    class Meta:
        ordering = ['cod_orden_fact']

    TIPO_CHOICES=[('Natural','Natural'),('Jurídica','Jurídica'),]
    

    tipo_cliente=models.CharField(max_length=15, choices=TIPO_CHOICES)
    cod_orden_fact=models.CharField(max_length=15, blank=True)
    n_tramite=models.CharField(max_length=15,blank=True, null=True, default='No asignado')
    fecha_tramite=models.DateField(blank=True, null=True)
    n_factura=models.CharField(max_length=15,blank=True, null=True, default='No asignado')
    fecha_factura=models.DateField(blank=True, null=True)
    fecha=models.DateField()
    ruc_ci=models.CharField(max_length=13)
    razon_nombres=models.CharField(max_length=200)
    contacto=models.CharField(max_length=200,blank=True, null=True)
    tipo_evento=models.CharField(max_length=15, choices=TIPO_EVENTO, null=True)
    #contacto=models.CharField(max_length=200)
    #direccion=models.CharField(max_length=200)
    #telefono=models.CharField(max_length=15)
    asesor=models.CharField(max_length=200,blank=True, null=True)

    centro_costos = models.ForeignKey(Centro_Costos, on_delete=models.SET_NULL, blank=False, null=True)
    n_participantes=models.PositiveIntegerField(blank=True, default=0, null=True)

    observaciones=models.CharField(max_length=500,blank=True, null=True)
    
    estado = models.CharField(max_length=5,default='ACTV',choices=ESTADO_CHOICES, blank=True, null=True)
    #participantes=models.ManyToManyField(Persona_Natural)
    subtotal=models.FloatField(blank=True, null=True ,default=0.0)
    descuento_fact=models.FloatField(blank=True, null=True,default=0.0)
    descuento_total=models.FloatField(blank=True, null=True,default=0.0)

    valor_total=models.FloatField(blank=True, null=True,default=0.0)
    valor_pendiente=models.FloatField(blank=True, null=True,default=0.0)
    motivo_anular = models.CharField(max_length=500, blank=True, null=True)

    def delete(self, *arg, **kwargs):
        
        super().delete(*arg,**kwargs)
    def __str__(self):
        return self.cod_orden_fact+" - "+self.razon_nombres

class OrdenFacturacionParticipante(models.Model):
    participante=models.ForeignKey(Persona_Natural,on_delete=models.SET_NULL, blank=False, null=True)
    nombre_evento=models.CharField(max_length=500)
    cod_evento=models.CharField(max_length=20)
    valor_evento=models.FloatField(default=0)
    descuento=models.IntegerField(default=0)
    valor=models.FloatField(default=0)
    orden=models.ForeignKey(OrdenFacturacion, on_delete=models.SET_NULL, blank=True, null=True)




class OrdenFacturacionFile(models.Model):
    file = models.FileField(upload_to='uploads/facturas/',blank=True, null=True)
    #file = models.CharField(max_length=50, blank=True,default=" ")
    #propuesta = models.ManyToManyField(PropuestaCorporativo, through='PropFileKey')
    orden=models.ForeignKey(OrdenFacturacion, on_delete=models.CASCADE)

financiero/orden_facturacion/views.py
from django.shortcuts import render,  redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView
from .models import OrdenFacturacion, Persona_Natural, Juridica, OrdenFacturacionParticipante, Contacto_natural
from .forms import OrdenFacturacionForm, OrdenFacturacionUpdateForm, OrdenFacturacionFinalForm, OrdenFacturacionParticipanteForm, FileForm, FileFormset
from django.template.loader import render_to_string
from django.http import JsonResponse, HttpResponseRedirect
from datetime import date
from django.views.decorators.csrf import ensure_csrf_cookie
from .filters import OrdenFacturacionFilter

# Create your views here.

def index(request):
    if (request.GET.get('estado',None)!=None and 'ANLD' in request.GET['estado']):
        ordFac_lista = OrdenFacturacion.objects.all()
    else:
        ordFac_lista = OrdenFacturacion.objects.all().exclude(estado='ANLD')
    ordFac_filter = OrdenFacturacionFilter(request.GET, queryset=ordFac_lista)
    #ordFac_filter = OrdenFacturacionFilter(request.GET, queryset=OrdenFacturacion.objects.all())
    return render(request, "orden_facturacion.html", {"filter":ordFac_filter})

class OrdenFacturacionCreate(CreateView):
    model=OrdenFacturacion
    form_class=OrdenFacturacionForm
    template_name='orden_facturacion_nuevo.html'
    success_url=reverse_lazy('orden_facturacion')

    def form_valid(self, form):
        
        try:
            pre=str(int(self.model.objects.latest('pk').pk+1))
            sec='0'*(4-len(pre))+pre
        except self.model.DoesNotExist:
            sec='0001'      
        print("jojo")
        print(form.instance.contacto)
        print("jeje")
        form.instance.cod_orden_fact=sec+'-'+str(date.today().year)
        form.instance.valor_pendiente = form.instance.valor_total
        return super().form_valid(form)
    
    def get_success_url(self, **kwargs):         
        return reverse_lazy('orden_facturacion_editar', args = (self.object.id,))

    """def get_context_data(self, **kwargs):
        context=super(OrdenFacturacionCreate,self).get_context_data(**kwargs)
        context['form']=self.form_class()
        context['formn']=self.pn_form_class()
        context['formj']=self.pj_form_class()

        return context"""

class OrdenFacturacionUpdate(UpdateView):
    model=OrdenFacturacion
    form_class=OrdenFacturacionUpdateForm
    second_form_class=OrdenFacturacionForm
    third_form_class=OrdenFacturacionFinalForm
    participantes_class=OrdenFacturacionParticipante
    template_name='orden_facturacion_editar.html'
    success_url=reverse_lazy('orden_facturacion')

    def get_context_data(self, **kwargs):
        context=super(OrdenFacturacionUpdate,self).get_context_data(**kwargs)
        pk=self.kwargs.get('pk',0)
        orden=self.model.objects.get(id=pk)
        participantes=self.participantes_class.objects.filter(orden_id=pk)
        context['participantes'] = participantes
        context['orden_id']=pk
        if self.request.POST:
            print("entro post")
            if 'form' in context:
                if orden.estado=='ACTV':
                    print("actv")
                    context['form']=self.second_form_class(self.request.POST,instance=orden)
                elif orden.estado=='PNDP':
                    print("pndp")
                    context['form']=self.third_form_class(self.request.POST,instance=orden)
                else:
                    print("else")
                    context['form']=self.form_class(self.request.POST,instance=orden)
            context['formset'] = FileFormset(self.request.POST, self.request.FILES,instance=self.object)
        else:
            if 'form' in context:
                if orden.estado=='ACTV':
                    print("actv")
                    context['form']=self.second_form_class(instance=orden)
                elif orden.estado=='PNDP':
                    print("pndp")
                    context['form']=self.third_form_class(instance=orden)
                else:
                    print("else")
                    context['form']=self.form_class(instance=orden)
            context['formset'] = FileFormset(instance=orden)
        return context

    def form_valid(self, form):
        form.instance.valor_pendiente = form.instance.valor_total
        pk=self.kwargs.get('pk',0)
        orden=self.model.objects.get(id=pk)
        if orden.estado=='ACPF':
            context = self.get_context_data()
            titles = context['formset']
            form.instance.created_by = self.request.user
            self.object = form.save()
            if titles.is_valid():
                titles.instance = self.object
                titles.save()
        return super().form_valid(form)

class OrdenFacturacionDelete(DeleteView):
    model=OrdenFacturacion
    template_name='orden_facturacion_eliminar.html'
    success_url=reverse_lazy('orden_facturacion')
    form_class=OrdenFacturacionForm
      

def orden_fact_conf_elim(request):
    orden_id=request.GET.get('pk')
    orden=OrdenFacturacion.objects.get(id=orden_id)
    print(orden.tipo_cliente)
    form=OrdenFacturacionForm(instance=orden)
    return render(request,"orden_facturacion_eliminar.html",{"orden":orden,"form":form})



def cambiar_estado(request, pk):
    orden=OrdenFacturacion.objects.get(id=pk)
    orden.estado='SLCE'
    orden.save()
    return HttpResponseRedirect(reverse_lazy('orden_facturacion'))

def verificar_campos(request):
    return render(request,"orden_facturacion_confirmar.html")

def load_personas(request):
    persona = request.GET.get("persona")
    identificacion=[]
    razon_nombre=[]
    if persona=="Natural":
        personas=Persona_Natural.objects.all()
        print(personas)
        identificacion=render_to_string("dropdown_natural_ci.html",{"personas":personas})
        razon_nombre=render_to_string("dropdown_natural_nombres.html",{"personas":personas})
    elif persona=="Jurídica":
        personas=Juridica.objects.all()
        print(personas)
        identificacion=render_to_string("dropdown_juridica_ruc.html",{"personas":personas})
        razon_nombre=render_to_string("dropdown_juridica_razon.html",{"personas":personas})
    return JsonResponse({'ruc_ci': identificacion, 'razon_nombre': razon_nombre})

def load_contactos(request):
    id = request.GET.get("id")
    contactos=Contacto_natural.objects.filter(empresa=id)
    
    listnatid=[]
    for c in contactos:
        listnatid.append(c.contacto.cedula)
        
    contactosN=Persona_Natural.objects.filter(cedula__in=listnatid)
    
    contlist=render_to_string("dropdown_contacto.html",{"contactos":contactosN})  
    return JsonResponse({'contacto': contlist})

def load_info(request):
    id = request.GET.get("id")
    persona= request.GET.get("persona")
    direccion=""
    telefono=""
    contacto=""
    sector=""
    tipo=""
    ##Para Natural
    email =""
    celular = ""
    cargo = ""

    if id!="":
        if persona=="Natural":
            cliente=Persona_Natural.objects.get(pk=id)
            direccion=cliente.dir_domicilio
            telefono=cliente.tel_domicilio
            celular=cliente.celular
            email = cliente.email
            cargo = cliente.cargo
        elif persona=="Jurídica":
            print("si entra")
            cliente=Juridica.objects.get(ruc=id)
            #direccion= cliente.direccion
            #telefono= cliente.telefono
            sector= cliente.sector.nombre
            tipo= cliente.tipo_empresa.nombre

    return JsonResponse({'direccion': direccion, 'telefono': telefono, 'contacto': contacto, 'sector': sector, 'tipo': tipo,'email':email,'celular':celular,'cargo':cargo})

def load_info_veris(request):
    id = request.GET.get("id")
    persona= request.GET.get("persona")
    direccion=""
    telefono=""
    contacto=""
    sector=""
    tipo=""
    ##Para Natural
    email =""
    celular = ""
    cargo = ""

    if id!="":
        if persona=="Natural":
            cliente=Persona_Natural.objects.get(pk=id)
            direccion=cliente.dir_domicilio
            telefono=cliente.tel_domicilio
            celular=cliente.celular
            email = cliente.email
            cargo = cliente.cargo
        elif persona=="Jurídica":
            
            cliente=Juridica.objects.get(ruc=id)
            direccion= cliente.direccion
            telefono= cliente.telefono
            email= cliente.correo
            sector= cliente.sector.nombre
            tipo= cliente.tipo_empresa.nombre
    return JsonResponse({'direccion': direccion, 'telefono': telefono, 'contacto': contacto, 'sector': sector, 'tipo': tipo,'email':email,'celular':celular,'cargo':cargo})

def load_mail(request):
    cedula = request.GET.get("cedula")
    print(cedula)
    email=""
    if cedula!="":
        email=Persona_Natural.objects.get(cedula=cedula).email
    return JsonResponse({"email": email})

def load_usuarios_ventas(request):
    usuariosv=""
    asesores=render_to_string("dropdown_usuarios_ventas.html",{"usuariosv":usuariosv})  
    return JsonResponse({'asesores': asesores})

def load_info_ci(request):
    pk = request.GET.get("pk")
    ci=""
    if id!="":
        ci=OrdenFacturacion.objects.get(id=pk).ruc_ci
    return JsonResponse({'ci': ci})


class ParticipanteCreate(CreateView):
    model=OrdenFacturacionParticipante
    form_class=OrdenFacturacionParticipanteForm
    template_name='nuevo_participante.html'
    success_url='/financiero/orden_facturacion/editar'

    def get_context_data(self, **kwargs):
        context=super(ParticipanteCreate,self).get_context_data(**kwargs)
        pk=self.kwargs.get('pk',0)
        context['orden_id']=pk
        context['orden_cod']=OrdenFacturacion.objects.get(pk=pk).cod_orden_fact
        return context

    def post(self, request,*args,**kwargs):
        self.object =self.get_object
        form=self.form_class(request.POST)
        if form.is_valid():

financiero/orden_facturacion/templates/dropdown_contacto.html
<option value="">---------</option>
{% for contacto in contactos %}
<option value="{{ contacto.cedula }}-{{ contacto.nombres }} {{ contacto.apellidos }}" name="{{ contacto.pk }}">{{ contacto.cedula }}-{{ contacto.nombres }} {{ contacto.apellidos }}</option>
{% endfor %}

financiero/orden_facturacion/templates/dropdown_usuarios_ventas.html
<option value="">---------</option>
<option value="Ikaros">Ikaros</option>
<option value="Nymph">Nymph</option>
<option value="Aestrea">Aestrea</option>
<option value="Chaos">Chaos</option>

financiero/orden_facturacion/templates/eliminar_participante.html
<div class="modal-header">
    <h5 class="modal-title" id="ordenTitle">Eliminación del participante</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<form method="POST" id="form-conf" action="{% url 'participante_eliminar' p.id orden_id %}">
{% csrf_token %}
<div class="modal-body">
    ¿Está segura que desea eliminar al siguiente participante?<br>
    {{p.participante}}
</div>
<div class="modal-footer">
    <button class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
    <button class="btn btn-danger mr-3" type="submit" id="conf">Eliminar</button>
</div>
</form>

financiero/orden_facturacion/templates/nuevo_participante.html
{% extends "base_financiero.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}{{ "EC - Orden Facturación Participante" }}{% endblock title %}


{% block content %}
<form method="POST" novalidate id="form-participante">
    {% csrf_token %}

    <h2 class="darkgreen-text text-uppercase">Agregar Participante a la orden {{orden_cod}}</h2>
    <div class="form-row">
        <div class="col-6 mb-0">
            {{ form.participante|as_crispy_field }}
        </div>
        <div class="col-2 mb-0">
            {{ form.cod_evento|as_crispy_field }}
        </div>
        <div class="col-2 mb-0">
            {{ form.nombre_evento|as_crispy_field }}
        </div>
        <div class="col-3 mb-0">
            {{ form.valor_evento|as_crispy_field }}
        </div>
        <div class="col-3 mb-0">
            {{ form.descuento|as_crispy_field }}
            <small class="form-text text-muted">Expresado en porcentaje</small>
        </div>

        <div class="col-3 mb-0">
            {{ form.valor|as_crispy_field }}
        </div>
    </div>
    <button id="hack" type="submit" class="btn btn-secondary green-bg">Guardar</button>
    <a class="btn btn-secondary" href="{% url 'orden_facturacion_editar' orden_id %}"> Cancelar </a>
</form>
{% endblock content %}

{% block extrafooter %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
<script src="{% static 'js/participante_evento.js' %}"></script>
<script src="{% static 'js/orden_money.js' %}"></script>
<!-- <script>
    var p_url = "";

    $('#id_participante').select2({
        minimumInputLength: 2,
        language: {
            noResults: function () {
                $(".select2-results__options").append("<a id='pnuevo' class='btn btn-secondary btn-block btn-sm' href='{% url 'natural_nuevo' %}' target='_blank'>Agregar Nuevo</a>");
                return "No hay resultados";
            },
            searching: function () {

                return "Buscando...";
            },
            inputTooShort: function (e) {
                var t = e.minimum - e.input.length;
                return "Ingresa " + t + " caractéres para buscar";
            }
        }
    });

    calcular();

    $('#id_valor_evento').change(function (e) {
        calcular();
    });

    $('#id_descuento').change(function (e) {
        calcular();
    });

    function roundToTwo(num) {
        return +(Math.round(num + "e+2") + "e-2");
    }
    function calcular() {
        var v_evento = $('#id_valor_evento').val();
        var desc = $("#id_descuento").val();

        if (v_evento == null || v_evento <= 0) {
            $("#id_valor").val(0.0);
            v_evento = 0;
        }
        if (desc == null || desc <= 0) {
            desc = 0;
        }
        desc = 1 - (desc / 100);
        v_evento *= desc;
        $("#id_valor").val(roundToTwo(v_evento));
    }
</script> -->

{% endblock extrafooter %}

financiero/orden_facturacion/templates/orden_facturacion_auth.html
{% extends "base_coordinador.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% load index %}

{% block title %}{{ "EC - Orden de facturación" }}{% endblock title %}


{% block content %}
<form method="POST" novalidate id="form-fact" enctype="multipart/form-data" ,
  data-persona-url="{% url 'ajax_load_personas' %}" data-confirmacion-url="{% url 'ajax_verificar_campos' %}"
  data-natural-url="{% url 'natural_nuevo'%}" data-juridica-url="{% url 'juridicas_view' %}"
  data-info-url="{% url 'ajax_info_veris_id' %}" data-mail-url="{% url 'ajax_load_mail' %}"
 >
  {% csrf_token %}
  {% block editar %}

  <div class="row mb-2">
    <div class="col-12">
      <h2 class="darkgreen-text text-uppercase">Registro de Orden de Facturación</h2>
    </div>
  </div>
  {% endblock editar %}
  <div class="row darkwhite-bg py-2">
    <div class="col-12">
      {{form.cod_orden_fact}}
      {{form.estado}}
      <div class="form-row">
        <div class="col-6 col-md-3 mb-0">
          {{ form.fecha|as_crispy_field }}
        </div>
        <div class="col-6 col-md-3 mb-0">

          {{form.tipo_cliente|as_crispy_field}}
          <small class="form-text text-muted">Seleccione el tipo de cliente</small>

        </div>
        <div class="col-6 col-md-3 mb-0 " id="field-ruc-ci">
          <div id="div_id_ruc_ci" class="form-group">
            <label for="{{ form.ruc_ci.id_for_label}}" class="col-form-label requiredField"
              id="ruc_ci">RUC/CI</label><span class="asteriskField">*</span>
            <div>
              {{ form.ruc_ci}}
              {% if form.ruc_ci.errors %}
              {% for error in form.ruc_ci.errors %}
              <p class="invalid-feedback d-block">
                <strong>{{ error }}</strong>
              </p>
              {% endfor %}
              {% endif %}

            </div>
          </div>
        </div>

        <div class="col-6 col-md-3 mb-0 " id="field-razon">
          <div id="div_id_razon_nombres" class="form-group">
            <label for="{{ form.razon_nombres.id_for_label}}" class="col-form-label requiredField" id="ra_nom">Razón
              Social/Nombres</label><span class="asteriskField">*</span>
            <div>
              {{ form.razon_nombres}}
              {% if form.razon_nombres.errors %}
              {% for error in form.razon_nombres.errors %}
              <p class="invalid-feedback d-block">
                <strong>{{ error }}</strong>
              </p>
              {% endfor %}
              {% endif %}

            </div>
          </div>
        </div>
      </div>
      <div class="form-row">
        <div class="col-12 col-md-3">
          {{ form.contacto|as_crispy_field }}
        </div>
        <div class="col-12 col-md-2">
          <label for="Email" class="col-form-label">Email</label>
          <input type="text" id="email" class="form-control" disabled>
        </div>
        <div class="col-12 col-md-6">
          <label for="direccion" class="col-form-label">Dirección</label>
          <input type="text" id="direccion" class="form-control" disabled>
        </div>
        <div class="col-12 col-md-3">
          <label for="telefono" class="col-form-label">Teléfono</label>
          <input type="text" id="telefono" class="form-control" disabled>
        </div>
        <input type="hidden" name="centro_costos" value='{{form.centro_costos.value}}' />
        <div class="col-6 col-md-4">{{ form.centro_costos|as_crispy_field }}</div>
        <div class="col-6 col-md-2">{{ form.tipo_evento|as_crispy_field }}</div>
        <div class="col-6 col-md-2">{{ form.asesor|as_crispy_field }}</div>
        {% block n_par %}
        {{ form.n_participantes}}
        {% endblock n_par %}
      </div>
      <div class="form-row">
        <div class="col-12 col-md-6">{{ form.observaciones|as_crispy_field }}</div>
      </div>

    </div>
  </div>
  {% block tablas %}

  <div class="mt-3">
    <button type="submit" class="btn btn-secondary green-bg">Siguiente</button>

    <!--<a class="btn btn-secondary " data-toggle='modal' data-target="#ordenAgregarCenter" href='#'
      id="confirmar_guardar">Guardar</a>-->
    <a class="btn btn-secondary" href="{% url 'orden_facturacion' %}">Cancelar</a>
  </div>
  {% endblock tablas %}


  {{ form.media }}
</form>
{% block confirmar%}
{% endblock confirmar%}

{% endblock content %}

{% block extrafooter %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
<script src="{% static 'js/orden_fact_form.js' %}"></script>

{% block anexos %}
{% endblock anexos %}

{% endblock extrafooter %}

financiero/orden_facturacion/templates/orden_facturacion_confirmar.html
¿Está seguro/a que desea continuar? Verifíque los datos ingresados antes de proceder.

financiero/orden_facturacion/templates/orden_facturacion_eliminar.html
<div class="modal-header">
    <h5 class="modal-title" id="ordenTitle">Anulación de factura {{orden.cod_orden_fact}}</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<form method="POST" action="{% url 'orden_facturacion_anularMenu' orden.id %}" >
    {% csrf_token %}

    <div class="modal-body">
        ¿Está segura que desea anular la siguiente orden de facturación?
        Código: {{orden.cod_orden_fact}}
        <br>
        Estado: {{orden.get_estado_display}}
        <br>
        <br>
        Ingrese el motivo de la anulación
        {{ form.motivo_anular }}
    </div>
    <div class="modal-footer">
        <button class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
        <button id="anular" class="btn btn-secondary green-bg mr-3" type="submit" disabled> Anular </button>
    </div>
</form>